### PR TITLE
fix: #14 - deprecated snake_case

### PR DESCRIPTION
**Pull request by williamdes**
Fixes: #14

### CODE REVIEW

**Comment by williamdes** [comment]
cc @pixelpeter 

this will allow laravel 6 support

The function exists since a very very long time https://laravel.com/api/4.2/Illuminate/Support/Str.html#method_snake

**Comment by williamdes** [comment]
@pixelpeter :ping_pong:

**Comment by williamdes** [comment]
@pixelpeter please click merge :sweat_smile: 
I want to delete my fork

**Comment by iadambrown** [comment]
🦗🦗🦗

**Comment by williamdes** [comment]
@pixelpeter :pray:

**Comment by williamdes** [comment]
@pixelpeter :no_mouth:

**Comment by royduin** [comment]
💤

**Comment by williamdes** [comment]
I will no longer wait.

**Comment by williamdes** [comment]
:ping_pong: who did think I would live without a fix being made :trollface: 

cc @pixelpeter

**Pull request closed without merging**
